import { Code, PackageHeader, Section } from '../../components'

const usageSnippet = `// Icons are generated by the pure-glyf Vite plugin from your SVG sources.
// Each import is a class name string; importing it injects the CSS automatically.
import { tablerSun, tablerMoon } from 'pure-glyf/icons'

// Use the class name directly on an element
<i class={tablerSun} />
<i class={tablerMoon} />

// With Sursaut icon props (Button icon=... etc.), register the factory once:
import { registerGlyfIconFactory } from 'pure-glyf/sursaut'
registerGlyfIconFactory()`

const setupSnippet = `// vite.config.ts
import { pureGlyfPlugin } from 'pure-glyf/plugin'

export default defineConfig({
  plugins: [
    pureGlyfPlugin({
      // Prefix -> directory of SVG sources
      icons: { Tabler: './icons/tabler' },
      // optional: dts defaults to '.generated-types/pure-glyf.d.ts'
    }),
  ],
})`

export default function PureGlyfUsagePage() {
	return (
		<article>
			<PackageHeader
				name="Pure-glyf Usage"
				description="Generating and consuming icons in your Sursaut application."
			/>

			<Section title="Basic Usage">
				<p>
					Icons are exported as string constants containing their CSS class name. Importing the icon
					triggers the IIFE that injects the required CSS into the document.
				</p>
				<Code code={usageSnippet} lang="tsx" />
			</Section>

			<Section title="Vite Plugin Setup">
				<p>
					Pure-glyf uses a Vite plugin to scan SVG directories and generate tree-shakeable icon
					modules. The generated <code>pure-glyf/icons</code> module exports one constant per icon.
				</p>
				<Code code={setupSnippet} lang="tsx" />
			</Section>

			<Section title="The CLI / Codegen">
				<p>
					You can generate your own icon sets from a directory of SVGs using the Pure-glyf CLI. It
					supports prefixing, path sanitization, and automatic <code>.d.ts</code> generation.
				</p>
			</Section>
		</article>
	)
}
