import { Code, PackageHeader, Section } from '../../components'

const adapterSetup = `import { sursautBarrelPlugin, sursautMinimalPackage } from '@sursaut/core/plugin'

export default defineConfig({
  plugins: [
    ...sursautMinimalPackage(),
    sursautBarrelPlugin({
      skeleton: 'front-end',
      adapter: '@sursaut/adapter-pico',
    }),
  ],
})

import '@picocss/pico/css/pico.min.css'
import '@sursaut/adapter-pico/css'`

const buttonExample = `import { Button } from '@sursaut'

// Headless behavior comes from @sursaut/ui models.
// The visual implementation comes from your adapter.
<Button variant="primary">Save</Button>
<Button variant="danger">Delete</Button>
<Button variant="success">Confirm</Button>

// Dot-syntax is generated by uiComponent(...)
<Button.primary>Save</Button.primary>

// Loading state via directive:
<Button use:loading={state.saving}>Submitting...</Button>

// With icons (via pure-glyf):
<Button icon="check">Save</Button>`

const overlayExample = `import { StandardOverlays } from '@sursaut/adapter-pico'

// Wrap your app with StandardOverlays:
<StandardOverlays>
  <App />
</StandardOverlays>

// Then use env.dialog / env.toast / env.drawer:
env.toast.success('Saved!')
env.toast.error('Something went wrong')

env.dialog({ title: 'Confirm', message: 'Are you sure?' })

env.drawer({ children: <SettingsPanel />, side: 'right' })`

const displayContext = `import type { Env } from '@sursaut/core'
import { DisplayProvider, useDisplayContext } from '@sursaut/kit'
import { ThemeToggle } from '@sursaut'
import { reactive } from 'mutts'

const settings = reactive({ theme: 'auto' as const })

function ThemeLabel(_props: {}, env: Env) {
  const dc = useDisplayContext(env)
  return <span>Resolved theme: {dc.theme}</span>
}

function App() {
  return (
    <DisplayProvider theme={settings.theme}>
      <ThemeToggle settings={settings} />
      <ThemeLabel />
    </DisplayProvider>
  )
}`

export default function UIPage() {
	return (
		<article>
			<PackageHeader
				name="@sursaut/ui"
				description="Headless primitives, directives, overlays, and models for adapter-driven Sursaut UIs."
			/>

			<p>
				<code>@sursaut/ui</code> is the headless layer of the Sursaut UI stack. It exports models,
				directives, overlays, and shared utilities; visual components come from an adapter such as{' '}
				<code>@sursaut/adapter-pico</code> and are typically consumed through the{' '}
				<code>@sursaut</code> front-end barrel.
			</p>
			<p>
				The palette runtime is documented separately because it lives on the dedicated{' '}
				<code>@sursaut/ui/palette</code> subpath rather than the root <code>@sursaut/ui</code>{' '}
				entry. See <a href="/ui/palette">Palette</a> for the current API.
			</p>

			<Section title="Adapter Setup">
				<p>
					Use a front-end barrel so your app imports from one place while the adapter decides the
					actual component implementation.
				</p>
				<Code code={adapterSetup} lang="tsx" />
			</Section>

			<Section title="Components & Overlay APIs">
				<p>
					The front-end barrel mainly exposes adapter-backed components. Overlays are usually
					consumed through env helpers provided by <code>StandardOverlays</code>, rather than by
					rendering <code>Dialog</code>, <code>Toast</code>, or <code>Drawer</code> directly.
				</p>
				<table>
					<thead>
						<tr>
							<th>Component</th>
							<th>Description</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<code>Button</code>
							</td>
							<td>Interactive button with variants, icons, loading state</td>
						</tr>
						<tr>
							<td>
								<code>ButtonGroup</code>
							</td>
							<td>Group buttons with shared styling</td>
						</tr>
						<tr>
							<td>
								<code>Accordion</code>
							</td>
							<td>Collapsible content section</td>
						</tr>
						<tr>
							<td>
								<code>Card</code>
							</td>
							<td>Content container with header/footer slots</td>
						</tr>
						<tr>
							<td>
								<code>Menu</code>
							</td>
							<td>Navigation menu with keyboard support</td>
						</tr>
						<tr>
							<td>
								<code>env.dialog(...)</code>
							</td>
							<td>Imperative dialog API exposed by the overlay host</td>
						</tr>
						<tr>
							<td>
								<code>env.toast(...)</code>
							</td>
							<td>Imperative toast API exposed by the overlay host</td>
						</tr>
						<tr>
							<td>
								<code>env.drawer(...)</code>
							</td>
							<td>Imperative drawer API exposed by the overlay host</td>
						</tr>
						<tr>
							<td>
								<code>Progress</code>
							</td>
							<td>Progress bar with indeterminate mode</td>
						</tr>
						<tr>
							<td>
								<code>InfiniteScroll</code>
							</td>
							<td>Virtualized list with variable height</td>
						</tr>
						<tr>
							<td>
								<code>Toolbar</code>
							</td>
							<td>Horizontal toolbar with spacer</td>
						</tr>
						<tr>
							<td>
								<code>Stars</code>
							</td>
							<td>Star rating input with single or range selection</td>
						</tr>
						<tr>
							<td>
								<code>Badge</code>
							</td>
							<td>Small uppercase status label</td>
						</tr>
						<tr>
							<td>
								<code>Pill</code>
							</td>
							<td>Medium status indicator with icons</td>
						</tr>
						<tr>
							<td>
								<code>Chip</code>
							</td>
							<td>Interactive dismissible token</td>
						</tr>
						<tr>
							<td>
								<code>CheckButton</code>
							</td>
							<td>Toggle button with role="checkbox" semantics</td>
						</tr>
						<tr>
							<td>
								<code>RadioButton</code>
							</td>
							<td>Button-style radio with group/value binding</td>
						</tr>
						<tr>
							<td>
								<code>Multiselect</code>
							</td>
							<td>Dropdown multi-selection with Set binding</td>
						</tr>
						<tr>
							<td>
								<code>Heading</code>
							</td>
							<td>Semantic heading (h1–h6) with variant coloring</td>
						</tr>
						<tr>
							<td>
								<code>Text</code>
							</td>
							<td>Paragraph text with size presets and muted mode</td>
						</tr>
						<tr>
							<td>
								<code>Link</code>
							</td>
							<td>Styled anchor with client-side routing</td>
						</tr>
						<tr>
							<td>
								<code>Icon</code>
							</td>
							<td>Icon rendering via adapter factory</td>
						</tr>
						<tr>
							<td>
								<code>Forms</code>
							</td>
							<td>Select, Combobox, Checkbox, Radio, Switch</td>
						</tr>
						<tr>
							<td>
								<code>Layout</code>
							</td>
							<td>Stack, Inline, Grid, AppShell, Container</td>
						</tr>
						<tr>
							<td>
								<code>@sursaut/ui/palette</code>
							</td>
							<td>Palette runtime, command-box helpers, and headless toolbar layout primitives</td>
						</tr>
					</tbody>
				</table>
			</Section>

			<Section title="Buttons">
				<Code code={buttonExample} lang="tsx" />
			</Section>

			<Section title="Overlay System">
				<p>
					Dialogs, toasts, and drawers use a shared overlay system. Inject{' '}
					<code>StandardOverlays</code> near the app root to enable <code>env.dialog</code>,{' '}
					<code>env.toast</code>, and <code>env.drawer</code>.
				</p>
				<Code code={overlayExample} lang="tsx" />
			</Section>

			<Section title="Display Context">
				<p>
					<code>DisplayProvider</code> and <code>useDisplayContext()</code> come from{' '}
					<code>@sursaut/kit</code>. <code>ThemeToggle</code> is adapter-backed and typically
					consumed through the front-end barrel. Together they resolve theme, direction, locale, and
					timezone for a subtree.
				</p>
				<Code code={displayContext} lang="tsx" />
			</Section>

			<Section title="Directives">
				<p>UI directives for common patterns:</p>
				<ul>
					<li>
						<code>use:badge</code> — badge overlay on any element
					</li>
					<li>
						<code>use:intersect</code> — intersection observer
					</li>
					<li>
						<code>use:loading</code> — loading state with spinner
					</li>
					<li>
						<code>use:pointer</code> — pointer event tracking
					</li>
					<li>
						<code>use:resize</code> — resize observer
					</li>
					<li>
						<code>use:scroll</code> — scroll position tracking
					</li>
					<li>
						<code>use:sizeable</code> — makes elements resizable by dragging
					</li>
					<li>
						<code>use:tail</code> — auto-scroll to bottom for chat logs
					</li>
				</ul>
			</Section>
		</article>
	)
}
